spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://config:8088"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: category
          uri: lb://category
          predicates:
            - Path=/api/categories/**
        - id: journal
          uri: lb://journal
          predicates:
            - Path=/api/journals/**
