apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal
  template:
    metadata:
      labels:
        app: journal
    spec:
      containers:
        - name: journal
          image: journal:1.0.0
          ports:
            - containerPort: 8081
      initContainers:
        - name: journal-postgres
          image: busybox
          command: ['sh', '-c', 'until nslookup postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done']
        - name: journal-eureka
          image: busybox
          command: [ 'sh', '-c', 'until nslookup eureka.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for eureka; sleep 2; done' ]
        - name: journal-config
          image: busybox
          command: [ 'sh', '-c', 'until nslookup config.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for config; sleep 2; done' ]

---
apiVersion: v1
kind: Service
metadata:
  name: journal
spec:
  selector:
    app: journal
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
